In [ ]:
#importing libraries 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('mymoviedb.csv',lineterminator='\n')

In [ ]:
df.head()

In [ ]:
df.info()

In [ ]:
df['Genre'].head()

In [ ]:
df.duplicated().sum() #checking duplicate values

In [ ]:
df.describe()

• Exploration Summary

 we have a dataframe consisting of 9827 rows and 9 columns.
our dataset looks a bit tidy with no NaNs nor duplicated values.
 Release_Date column needs to be casted into date time and to extract only the year value.
Overview, Original_Language and Poster-Url wouldn't be useful during analysis, so we'll drop them.
there is noticeable outliers in Popularity column
 Vote_Average better be categorised for proper analysis. 
 Genre column has comma seperated values and white spaces that needs to be handled and casted into category.

In [ ]:
df.head()

In [ ]:
# preprocessing - changing release date to datetime format
df['Release_Date'] = pd.to_datetime(df['Release_Date'])
print(df['Release_Date'].dtypes)

In [ ]:
# keeping only year
df['Release_Date'] = df['Release_Date'].dt.year
df['Release_Date'].dtypes

dropping the columns

In [ ]:
cols=['Overview','Original_Language','Poster_Url']

cols contains the names of all columns that we want to remove

In [ ]:
df.drop(cols, axis=1 , inplace = True)
df.columns

In [ ]:
df.head()

Categorizing Vote_Average column
We would cut the Vote_Average values and make 4 categories : popular, average, below_avg, not_popular to describe it more using categorize_col() function provided above.

In [ ]:
def categorize_col(df,cols,labels):
    edges= [df[cols].describe()['min'],
            df[cols].describe()['25%'],
            df[cols].describe()['50%'],
            df[cols].describe()['75%'],
            df[cols].describe()['max']]
    df[cols]=pd.cut(df[cols], edges, labels=labels, duplicates='drop')
    return df

In [ ]:
labels=['not_popular','below_avg','average','popular']
categorize_col(df,'Vote_Average',labels)
df['Vote_Average'].unique()

In [ ]:
df.head()

In [ ]:
df['Vote_Average'].value_counts() # checking how many movies are in each label

In [ ]:
df.dropna(inplace=True)
df.isna().sum()  #removing all duplicates and Nan values

In [ ]:
df.head()

We would split the genres into a list and then explode our dataframe to have only one genre per row for each movie

In [ ]:
df['Genre'] = df['Genre'].str.split(', ')
df= df.explode('Genre').reset_index(drop=True)
df.head()

In [ ]:
#casting columns to categories
df['Genre'] = df['Genre'].astype('category')
df['Genre'].dtypes

In [ ]:
df.info()

In [ ]:
df.nunique()

# DATA VISUALIZATION

In [ ]:
sns.set_style('whitegrid')

1) What is the most frequent genre of movies released on Netflix?

ans) Most frequent type of movies released is of Drama Genre.

In [ ]:
df['Genre'].describe()

In [ ]:
sns.catplot(y= 'Genre', data = df, kind = 'count',
            order = df['Genre'].value_counts().index,
            color = '#FFB6C1')
plt.title("Genre column distribution")
plt.show()

2) Which has the highest vote in the vote_avg column?
 ans) average

In [ ]:
sns.catplot(y='Vote_Average', data = df , kind= 'count',
            order = df['Vote_Average'].value_counts().index,
            color='#C8A2C8')
plt.title("Vote Distribution")
plt.show()

3) What movie got the highest popularity?What is its genre?

In [60]:
df.head(2)

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Genre
0,2021,Spider-Man: No Way Home,5083.954,8940,popular,Action
1,2021,Spider-Man: No Way Home,5083.954,8940,popular,Adventure

In [61]:
df[df['Popularity'] == df['Popularity'].max()]

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Genre
0,2021,Spider-Man: No Way Home,5083.954,8940,popular,Action
1,2021,Spider-Man: No Way Home,5083.954,8940,popular,Adventure
2,2021,Spider-Man: No Way Home,5083.954,8940,popular,Science Fiction

4) Which movie got lowest popularity? Whats it Genre?

In [62]:
df[df['Popularity'] == df['Popularity'].min()]

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Genre
25546,2021,The United States vs. Billie Holiday,13.354,152,average,Music
25547,2021,The United States vs. Billie Holiday,13.354,152,average,Drama
25548,2021,The United States vs. Billie Holiday,13.354,152,average,History
25549,1984,Threads,13.354,186,popular,War
25550,1984,Threads,13.354,186,popular,Drama
25551,1984,Threads,13.354,186,popular,Science Fiction

5) Which year has the most filmed movies?

Conclusion

Q 1: What is the most frequent genre in the data set?
Drama genre is the most frequent genre in our data set and has appeared more than 14% of the times among 19 other genres.

Q 2: What genres has highest votes?
we have 25.5% of our data set with popular vote (6520 rows). Drama again gets the highest popularity among fans by being having more than 18.5% of movies popularities.

Q 3: What movie got the highest popularity? what's its genre?
Spider-Man: No Way Home has the highest popularity rate in our data set and it has genres of Action, Adventure and Science Fiction.

Q 3: What movie got the lowest popularity? what's its genre?
The united states, thread' has the highest lowest rate in our data set and it has genres of music, drama, 'war', 'sci-fi' and history'.

Q 4: Which year has the most filmed movies?
year 2020 has the highest filming rate in our data set.